apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment-0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-0
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-0
    spec:
      containers:
      - name: sample-app-container-0
        image: swr.la-south-2.myhuaweicloud.com/hwperu/test-jenkins:$BUILD_NUMBER
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: default-secret
