apiVersion: v1 
kind: Service 
metadata:
  labels:
    app: sample-deployment-0
    name: svc-example
  name: svc-example
  namespace: default
spec:
  externalTrafficPolicy: Local
  ports:
  - name: cce-service-0
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: test-0
  sessionAffinity: None
  type: NodePort
